baseURL = 'https://s-video.github.io'
languageCode = 'en-us'
title = "Andrew's Blog"
publishDir = 'docs'
theme = 'etch'

[params]
  mainSections = ['posts']

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:slug/"